service: naver-news-alarm
frameworkVersion: '3'
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    NAVER_NEWS_CLIENT_ID:
    NAVER_NEWS_SECRET_KEY:
    NAVER_URL_CLIENT_ID:
    NAVER_URL_SECRET_KEY:

functions:
  check:
    handler: handler.check
    events:
      - httpApi:
          path: /check
          method: get
  news:
    handler: handler.news
    events:
      - httpApi:
          path: /news
          method: get
