# NodeJS Version 16
FROM node:20.8.0-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV production
EXPOSE 3000

RUN npm run build

# Cmd script
CMD ["npm", "run", "start:prod"]
